version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=owncloud
    - DB_PASS=password
    - DB_NAME=owncloud_db
    volumes:
    - /srv/docker/owncloud/postgresql:/var/lib/postgresql

  owncloud:
    restart: always
    image: sameersbn/owncloud:10.0.8
    command: app:owncloud
    environment:
    - DEBUG=false
    - TZ=Asia/Kolkata

    - DB_TYPE=pgsql
    - DB_HOST=postgresql
    - DB_USER=owncloud
    - DB_PASS=password
    - DB_NAME=owncloud_db

    - OWNCLOUD_URL=http://cloud.example.com:10080

    - OWNCLOUD_ADMIN_USER=
    - OWNCLOUD_ADMIN_PASSWORD=

    - OWNCLOUD_UPLOAD_MAX_FILESIZE=4G
    - OWNCLOUD_MAX_FILE_UPLOADS=20

    - OWNCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
    - /srv/docker/owncloud/owncloud:/var/lib/owncloud

  nginx:
    restart: always
    image: sameersbn/owncloud:10.0.8
    command: app:nginx
    environment:
    - OWNCLOUD_PHP_FPM_HOST=owncloud
    - OWNCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - owncloud
    ports:
    - "10080:80"
