postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-20
  environment:
    - DB_USER=owncloud
    - DB_PASS=password
    - DB_NAME=owncloud_db
  volumes:
    - /srv/docker/owncloud/postgresql:/var/lib/postgresql

owncloud:
  restart: always
  image: sameersbn/owncloud:9.0.1-2
  command: app:owncloud
  environment:
    - DEBUG=false
    - TZ=Asia/Kolkata

    - OWNCLOUD_URL=http://cloud.example.com:10080

    - OWNCLOUD_ADMIN_USER=
    - OWNCLOUD_ADMIN_PASSWORD=

    - OWNCLOUD_UPLOAD_MAX_FILESIZE=4G
    - OWNCLOUD_MAX_FILE_UPLOADS=20

    - OWNCLOUD_BACKUPS_EXPIRY=0
  links:
    - postgresql:postgresql
  volumes:
    - /srv/docker/owncloud/owncloud:/var/lib/owncloud

nginx:
  image: sameersbn/owncloud:9.0.1-2
  command: app:nginx
  environment:
    - OWNCLOUD_PHP_FPM_HOST=
    - OWNCLOUD_PHP_FPM_PORT=
  links:
    - owncloud:php-fpm
  ports:
    - "10080:80"
