apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  containers:
    - name: postgresql
      image: sameersbn/postgresql:9.5-3
      env:
        - name: DB_USER
          value: owncloud
        - name: DB_PASS
          value: password
        - name: DB_NAME
          value: owncloud_db
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 30
        timeoutSeconds: 5
  volumes:
    - name: data
      emptyDir: {}
